### ISSUE TITLE
Unexpected Circular Import

### ISSUE THREAD

**Issue by notanerd314** [AttackingOrDefending/python-tictactoe#8]
When I try importing `Board` from the package `tictactoe` like this:
```py
from tictactoe import Board
```
Python cannot import `Board` from `tictactoe` because it is a circular import, the error looks like this:
```
Traceback (most recent call last):
  File "c:\Users\...\tictactoe.py", line 1, in <module>
    import tictactoe
  File "c:\Users\...\tictactoe.py", line 2, in <module>
    from tictactoe import Board
ImportError: cannot import name 'Board' from partially initialized module 'tictactoe' (most likely due to a circular import) (c:\Users\...\tictactoe.py)
```
Can anyone please explain to me why?
**Note: There are those `...` in the error because I don't want to show my absolute path location.**

**Comment by AttackingOrDefending** [comment]
What is your python version?

**Comment by AttackingOrDefending** [comment]
There is a problem with python 3.6. If you are using it, please upgrade to python 3.7 or later.

**Comment by notanerd314** [comment]
3.12
________________________________

**Comment by AttackingOrDefending** [comment]
You have named your python file `tictactoe.py`. `tictactoe` is also the name of the library and that causes problems. Try chnanging the filename (e.g. to `tic_tac_toe.py`).

**Comment by notanerd314** [comment]
Cool thanks
________________________________
